---
title: NICE EnginFrame
short_title: EnginFrame
paras:
 - >-
   Your cluster has been configured with NICE EnginFrame, an advanced,
   commercially supported HPC Portal in the industry, with a proven
   track record of successful production deployments within corporate
   networks and research clusters.
 - >-
   Please visit the <a
   href="http://www.nice-software.com/products/enginframe">NICE
   website</a> for further information.
 - >-
   You can <a href="/enginframe">access EnginFrame by clicking here</a>.
