#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

main() {
  local master_ip token
  distro_start_service docker

  files_load_config instance config/cluster

  if [[ "${cw_INSTANCE_role}" == "master" ]]; then
    mkdir -p /opt/gridware/docker/swarm

    master_ip=$(network_get_iface_address "$(network_get_first_iface)")

    docker swarm init --advertise-addr "${master_ip}" > /dev/null
    docker swarm join-token -q worker > /opt/gridware/docker/swarm/token
    docker network create -d overlay --attachable gridware-mpi > /dev/null
    # TODO - specify a subnet for docker to use
  else
    if [ -f /opt/gridware/docker/swarm/token ]; then
      files_load_config --optional config config/cluster
      token=$(cat /opt/gridware/docker/swarm/token)
      docker swarm join --token "${token}" "${cw_CLUSTER_master}:2377" > /dev/null
    else
      action_die "No Swarm token found at /opt/gridware/docker/swarm/token - cannot join swarm."
    fi
  fi
}

setup

require distro
require files
require network
