#!/bin/bash
#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
hook="$1"
role="$2"
cluster_name="$3"
member_metafile="$4"

if [ ! -f "${member_metafile}" ]; then
    member_metafile=${member_metafile%%.*}
fi
. "${member_metafile}"

if [ "${cw_MEMBER_role}" == "mds" ]; then
    case $role in
        mds)
            :
            ;;
        oss)
            /opt/beegfs/sbin/beegfs-setup-storage \
                -p /data/ost -m ${cw_MEMBER_ip}
            # We no longer use the following parameters, as BeeGFS
            # will assign these automagically to free identities:
            # -s 1 -i 101
            /etc/init.d/beegfs-storage start
            ;;
        *)
            # CLIENT
            /opt/beegfs/sbin/beegfs-setup-client -m ${cw_MEMBER_ip}
            /etc/init.d/beegfs-helperd start
            tgts=$(beegfs-ctl --listnodes --nodetype=storage | wc -l)
            while [ $tgts -lt 1 ]; do
                echo "Waiting for storage targets to appear."
                sleep 1
                tgts=$(beegfs-ctl --listnodes --nodetype=storage | wc -l)
            done
            /etc/init.d/beegfs-client restart
            ;;
    esac
fi
