#!/bin/bash
#==============================================================================
# Copyright (C) 2016 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Clusterware.
#
# Alces Clusterware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Clusterware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Clusterware, please visit:
# https://github.com/alces-software/clusterware
#==============================================================================
setup() {
    local a xdg_config
    IFS=: read -a xdg_config <<< "${XDG_CONFIG_HOME:-$HOME/.config}:${XDG_CONFIG_DIRS:-/etc/xdg}"
    for a in "${xdg_config[@]}"; do
        if [ -e "${a}"/clusterware/config.rc ]; then
            source "${a}"/clusterware/config.rc
            break
        fi
    done
    if [ -z "${cw_ROOT}" ]; then
        echo "$0: unable to locate clusterware configuration"
        exit 1
    fi
    kernel_load
}

_configure_home_volume() {
    local dev
    dev=$1
    echo "Configuring home volume (${dev})"
    mkfs.ext4 -m0 -L home ${dev}
    mount ${dev} /mnt
    mv /home/* /mnt
    umount /mnt
    mount ${dev} /home
    echo "${dev} /home ext4 defaults 0 0" >> /etc/fstab
}

_configure_apps_volume() {
    local dev
    dev=$1
    echo "Configuring apps volume (${dev})"
    mkfs.ext4 -m0 -L applications ${dev}
    files_load_config --optional gridware
    cw_GRIDWARE_root="${cw_GRIDWARE_root:-/opt/gridware}"
    mkdir -p "${cw_GRIDWARE_root}"
    mount ${dev} /opt/gridware
    if [ -d /opt/apps ]; then
        mkdir /opt/gridware/.apps
        mv /opt/apps/* /opt/gridware/.apps
        mount -o bind /opt/gridware/.apps /opt/apps
    fi
    echo "${dev} ${cw_GRIDWARE_root} ext4 defaults 0 0" >> /etc/fstab
    echo "${cw_GRIDWARE_root}/.apps /opt/apps none defaults,bind 0 0" >> /etc/fstab
}

main() {
    if [ -b /dev/xvdp ]; then
        _configure_home_volume /dev/xvdp
    elif [ -b /dev/sdp ]; then
        _configure_home_volume /dev/sdp
    fi

    if [ -b /dev/xvdq ]; then
        _configure_apps_volume /dev/xvdq
    elif [ -b /dev/sdq ]; then
        _configure_apps_volume /dev/sdq
    fi
}

setup
require files

main "$@"
